{
"count": 11301,
"results": [
{
"listing_id": 104667996,
"state": "active",
"user_id": 7142451,
"category_id": 68887752,
"title": "Vintage Insta Mysan Athletes Foot Ringworm Medicine Emory Station Atlanta GA",
"description": "These are vintage boxes, not repros.  They have been stored away for years.  These come from a supply that furnishes restaurants like Cracker Barrel.  There is nothing inside, it is just the advertising box.  The box is in good condition, it has a place on the front left where the top level of paper is torn off and it has some rough edges.  I have two others that don&#39;t have a stain on them.  I will send out the best first.  It is 3 1/2  inches tall by  1 5/8 inches wide by 1 1/4 inch deep.  \nThis stuff was 70% alcohol, it would cure all!!\n\nPlease message me with any questions you may have.  \n\nThank you for visiting my shop and viewing my items!\n\nPlease visit my other Etsy shop  www.etsy.com/shop/TsVintique",
"creation_tsz": 1444614779,
"ending_tsz": 1455245579,
"original_creation_tsz": 1342585749,
"last_modified_tsz": 1444614781,
"price": "3.00",
"currency_code": "USD",
"quantity": 3,
"tags": [
"ad",
"advertise",
"advertisement",
"box",
"old",
"athletes foot",
"ringworm",
"itch"
],
"category_path": [
"Supplies",
"Scrapbooking"
],
"category_path_ids": [
69150433,
68887752
],
"materials": [
"card board",
"paper"
],
"shop_section_id": 7945750,
"featured_rank": null,
"state_tsz": 1353304744,
"url": "https://www.etsy.com/listing/104667996/vintage-insta-mysan-athletes-foot?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 11,
"num_favorers": 1,
"shipping_template_id": null,
"processing_min": null,
"processing_max": null,
"who_made": "someone_else",
"is_supply": "false",
"when_made": "1930s",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": "in",
"is_private": false,
"recipient": null,
"occasion": null,
"style": null,
"non_taxable": false,
"is_customizable": false,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": false,
"taxonomy_id": 731,
"taxonomy_path": [
"Craft Supplies & Tools",
"Scrapbooking Supplies"
],
"used_manufacturer": false
},
{
"listing_id": 251533521,
"state": "active",
"user_id": 47185179,
"category_id": 68888548,
"title": "Atlanta Falcons Charms",
"description": "Atlanta Falcons Bracelet/ Necklace Charms",
"creation_tsz": 1444614022,
"ending_tsz": 1455244822,
"original_creation_tsz": 1444614022,
"last_modified_tsz": 1444614097,
"price": "10.00",
"currency_code": "USD",
"quantity": 10,
"tags": [
"black",
"red",
"Stacking Bracelets",
"charm "
],
"category_path": [
"Jewelry",
"Bracelet"
],
"category_path_ids": [
68887482,
68888548
],
"materials": [
"charms",
"silver"
],
"shop_section_id": null,
"featured_rank": null,
"state_tsz": 1444614022,
"url": "https://www.etsy.com/listing/251533521/atlanta-falcons-charms?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 0,
"num_favorers": 0,
"shipping_template_id": 17313444012,
"processing_min": null,
"processing_max": null,
"who_made": "someone_else",
"is_supply": "false",
"when_made": "before_1996",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": null,
"is_private": false,
"recipient": null,
"occasion": null,
"style": null,
"non_taxable": false,
"is_customizable": false,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": false,
"taxonomy_id": 1197,
"taxonomy_path": [
"Jewelry",
"Bracelets",
"Charm Bracelets"
],
"used_manufacturer": false
},
{
"listing_id": 63879101,
"state": "active",
"user_id": 7230624,
"category_id": 69183817,
"title": "Womens Scarf Chunky Wool Cowl Oversized Button Cowl Scarf Wrap Wishbone Cowl Women&#39;s Fashion  Accessories - Vanilla Cream or CHOOSE Color",
"description": "I handmake the WishBone Cowl with a fabulously thick Lambswool blend that is so soft, plush, and warm. \r\n\r\nThis originally-designed Cowl is totally chic with great style. Can be worn to the side for an avant garde look or down for a more classic look. I enclose it with an oversized polished black Oval Ebony Wood button. Cowl can be unbuttoned for easy wear. \r\n\r\nFeatured in a beautiful Vanilla Cream color but several colors to choose from.\r\n--View Color Chart for all the color choices. Please indicate your color choice in the &quot;message to seller&quot; field during checkout. \r\n\r\n**I make and ship this item within 7 business days of your checkout date (see Hopme page for any additional lead times).\r\n\r\n\r\n♦♦♦♦♦♦♦♦♦♦♦♦♦♦\r\nClick to see my whole shop.\r\nswakcouture.etsy.com\r\n♦♦♦♦♦♦♦♦♦♦♦♦♦♦\r\nThanks for shopping!\r\nAmina",
"creation_tsz": 1444613612,
"ending_tsz": 1455244412,
"original_creation_tsz": 1291781496,
"last_modified_tsz": 1444613612,
"price": "49.00",
"currency_code": "USD",
"quantity": 5,
"tags": [
"knit",
"chunky",
"crochet",
"oversized cowl",
"avant garde cowl",
"wishbone cowl",
"gaetsyteam atlanta",
"tftateam",
"wedding cowl",
"weddings",
"chunky cowl",
"swakdesigns",
"neckwarmer"
],
"category_path": [
"Accessories",
"Scarf",
"Cowl"
],
"category_path_ids": [
69150467,
68892184,
69183817
],
"materials": [],
"shop_section_id": 6620533,
"featured_rank": null,
"state_tsz": 1440224217,
"url": "https://www.etsy.com/listing/63879101/womens-scarf-chunky-wool-cowl-oversized?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 5586,
"num_favorers": 276,
"shipping_template_id": null,
"processing_min": null,
"processing_max": null,
"who_made": "i_did",
"is_supply": "false",
"when_made": "2010_2015",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": null,
"is_private": false,
"recipient": null,
"occasion": null,
"style": null,
"non_taxable": true,
"is_customizable": true,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": false,
"suggested_taxonomy_id": 46,
"taxonomy_path": [
"Accessories",
"Scarves & Wraps",
"Scarves"
],
"used_manufacturer": false
},
{
"listing_id": 236667596,
"state": "active",
"user_id": 66243305,
"category_id": 68887648,
"title": "HARVESTER: ATLANTA CHRISTIAN College 1995 Yearbook, East Point, Georgia",
"description": "In Very Good Condition. No writing on any of the pages. 100% FULLY GUARANTEED.",
"creation_tsz": 1444613432,
"ending_tsz": 1455244232,
"original_creation_tsz": 1433985970,
"last_modified_tsz": 1444613432,
"price": "19.77",
"currency_code": "USD",
"quantity": 1,
"tags": [],
"category_path": [
"Books and Zines",
"Book"
],
"category_path_ids": [
69150385,
68887648
],
"materials": [],
"shop_section_id": null,
"featured_rank": null,
"state_tsz": 1444273209,
"url": "https://www.etsy.com/listing/236667596/harvester-atlanta-christian-college-1995?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 1,
"num_favorers": 1,
"shipping_template_id": 12949077726,
"processing_min": 1,
"processing_max": 2,
"who_made": "someone_else",
"is_supply": "false",
"when_made": "1990_1995",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": "in",
"is_private": false,
"recipient": null,
"occasion": null,
"style": null,
"non_taxable": false,
"is_customizable": false,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": false,
"taxonomy_id": 350,
"taxonomy_path": [
"Books, Movies & Music",
"Books",
"Reference Books"
],
"used_manufacturer": false
},
{
"listing_id": 251639602,
"state": "active",
"user_id": 6862566,
"category_id": 68890908,
"title": "Old Sweet Song (Georgia) 5x7",
"description": "This painting is a perfect addition to any Georgia Peach&#39;s space!  It is a 5x7 original water color on acid free, durable, water color paper with &quot;just an old sweet song&quot; handwritten in black ink.\n\nOriginal Artwork by Gini Bramlett ©2015 ginisis - All rights reserved. Purchasing this piece will not transfer reproduction rights. \n\nRemember colors may differ a little on your computer screen from the actual piece.",
"creation_tsz": 1444613107,
"ending_tsz": 1455243907,
"original_creation_tsz": 1444613072,
"last_modified_tsz": 1444613107,
"price": "8.00",
"currency_code": "USD",
"quantity": 1,
"tags": [
"Savannah",
"original",
"orange",
"painting",
"state",
"atlanta",
"peaches",
"peach",
"handwriting",
"watercolor",
"georgia",
"black ink",
"peachy"
],
"category_path": [
"Art",
"Painting"
],
"category_path_ids": [
68887312,
68890908
],
"materials": [
"watercolor",
"ink"
],
"shop_section_id": 13845941,
"featured_rank": null,
"state_tsz": 1444613072,
"url": "https://www.etsy.com/listing/251639602/old-sweet-song-georgia-5x7?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 0,
"num_favorers": 0,
"shipping_template_id": null,
"processing_min": null,
"processing_max": null,
"who_made": "i_did",
"is_supply": "false",
"when_made": "2010_2015",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": "in",
"is_private": false,
"recipient": null,
"occasion": null,
"style": null,
"non_taxable": false,
"is_customizable": false,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": false,
"taxonomy_id": 114,
"taxonomy_path": [
"Art & Collectibles",
"Painting",
"Watercolor"
],
"used_manufacturer": false
},
{
"listing_id": 193923347,
"state": "active",
"user_id": 5125634,
"category_id": 68930904,
"title": "Sexy handmade with NFL Atlanta Falcons fabric with scalloped lace accent top with matching G string lingerie set",
"description": "This is not a licensed NFL product.  It is however, handcrafted from NFL fabric.  I am not affiliated with or sponsored by NFL or it&#39;s affiliates.\n\nSexy handmade with NFL fabric Lace Set !!!\n\nFabric: 100% NFL Cotton with scalloped sheer lace border\n\nDescription: Very Sexy handmade to order scalloped lace top with a matching Y back lace band g string. The top of this is designed with NFL fabric and sheer scalloped lace accents ties around the neck and back for a great fit. The bottom is wide scallop lace band with a string back. We will be happy to answer any questions before your purchase. \n\nThis lace set is available from size XXS-XS , Small, Medium, and Large.  And bra tops ranging from A - DD Cup.  Please see the size chart.  \n\n It will be custom made for you within 3 to 5 business days.\n\n\nDisclaimer: Our garments are handmade from NFL licensed 100%  cotton fabric and we have no affiliation with the NFL or it&#39;s affiliates",
"creation_tsz": 1444612903,
"ending_tsz": 1455243703,
"original_creation_tsz": 1403470450,
"last_modified_tsz": 1444612903,
"price": "37.99",
"currency_code": "USD",
"quantity": 4,
"tags": [
"NFL Dress",
"NFL Lingerie",
"Sexy NFL",
"Custom made to order",
"NFL intimates",
"NFL baby doll",
"NFL g string",
"lingerie",
"sexy lingerie",
"NFL lace",
"NFL Lace set",
"NFL lace top",
"Handmade"
],
"category_path": [
"Clothing",
"Women",
"Lingerie"
],
"category_path_ids": [
69150353,
69152559,
68930904
],
"materials": [
"sheer mesh",
"black sheer mesh",
"Liscensed 100 percent NFL cotton"
],
"shop_section_id": 16193221,
"featured_rank": null,
"state_tsz": 1443029075,
"url": "https://www.etsy.com/listing/193923347/sexy-handmade-with-nfl-atlanta-falcons?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 370,
"num_favorers": 14,
"shipping_template_id": 694211744,
"processing_min": 3,
"processing_max": 5,
"who_made": "i_did",
"is_supply": "false",
"when_made": "made_to_order",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": "in",
"is_private": false,
"recipient": null,
"occasion": null,
"style": null,
"non_taxable": false,
"is_customizable": true,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": true,
"taxonomy_id": 511,
"taxonomy_path": [
"Clothing",
"Women's Clothing",
"Lingerie"
],
"used_manufacturer": false
},
{
"listing_id": 204267552,
"state": "active",
"user_id": 47126928,
"category_id": 68887486,
"title": "ATLANTA FALCONS Head Football Logo Face Shirt Jacket Backpack Emblem Badge Embroidered Sew or Iron on Patch Fast USA Shipping 2.6&quot; x 2.5&quot;",
"description": "FAST SHIPPING FROM USA! GREAT QUALITY!\n\nAll Items ship within 24 hours of purchase\n\nThis patch is 2.6&quot; x 2.5&quot;\nIt is new and unused and in perfect condition\nYou can iron it or sew it\nIt is 100% embroidered and very high quality\n\nIf you have any questions feel free to get in touch\nWe appreciate your business and hope to see you again...",
"creation_tsz": 1444612546,
"ending_tsz": 1455243346,
"original_creation_tsz": 1411269160,
"last_modified_tsz": 1444612546,
"price": "2.49",
"currency_code": "USD",
"quantity": 7,
"tags": [],
"category_path": [
"Patterns"
],
"category_path_ids": [
68887486
],
"materials": [],
"shop_section_id": 15436003,
"featured_rank": null,
"state_tsz": 1441146999,
"url": "https://www.etsy.com/listing/204267552/atlanta-falcons-head-football-logo-face?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 327,
"num_favorers": 9,
"shipping_template_id": null,
"processing_min": 1,
"processing_max": 1,
"who_made": "collective",
"is_supply": "false",
"when_made": "2010_2015",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": "in",
"is_private": false,
"recipient": null,
"occasion": null,
"style": null,
"non_taxable": false,
"is_customizable": false,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": false,
"taxonomy_id": 729,
"taxonomy_path": [
"Craft Supplies & Tools",
"Patterns & Tutorials"
],
"used_manufacturer": false
},
{
"listing_id": 202270247,
"state": "active",
"user_id": 33182386,
"category_id": 68888548,
"title": "Atlanta Falcons NFL Themed Glass and Ceramic Beaded Bracelet",
"description": "This stretch bracelet is made of round 8mm white opaque coated Czech glass pearl round beads, round 10mm red opaque coated Czech glass pearl round beads, 10mm round black glass beads, 8mm round Crystazzi light gray pearl beads, white rondel glass beads and a 15mm x 10mm hand crafted and hand painted ceramic football that was crafted by expert Peruvian craftspeople. The clay was shaped, fired, painted and glazed, then fired a second time for a true ceramic hardness. You can purchase this bracelet with or without the officially licensed NFL charm. Prices vary by selection. This bracelet will fit almost any wrist, but let me know if you need a specific size.",
"creation_tsz": 1444611966,
"ending_tsz": 1455242766,
"original_creation_tsz": 1409795603,
"last_modified_tsz": 1444611966,
"price": "16.00",
"currency_code": "USD",
"quantity": 2,
"tags": [
"unisex",
"stone beads",
"beaded",
"bracelet",
"stretch bracelet",
"NFL",
"glass beaded",
"NFL charm",
"football bracelet",
"ceramic football",
"football fan",
"Atlanta Falcons"
],
"category_path": [
"Jewelry",
"Bracelet"
],
"category_path_ids": [
68887482,
68888548
],
"materials": [
"stretch magic cord",
"split jump ring",
"jump ring",
"Peruvian ceramic football bead",
"official licensed NFL charm",
"white glass rondel beads",
"white glass beads",
"opaque coated Czech glass beads",
"red glass beads",
"black glass beads",
"Crystazzi light gray pearl beads"
],
"shop_section_id": 15923940,
"featured_rank": null,
"state_tsz": 1413382564,
"url": "https://www.etsy.com/listing/202270247/atlanta-falcons-nfl-themed-glass-and?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 20,
"num_favorers": 2,
"shipping_template_id": 1097721809,
"processing_min": 1,
"processing_max": 1,
"who_made": "i_did",
"is_supply": "false",
"when_made": "2010_2015",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": null,
"is_private": false,
"recipient": null,
"occasion": null,
"style": null,
"non_taxable": false,
"is_customizable": false,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": false,
"taxonomy_id": 1195,
"taxonomy_path": [
"Jewelry",
"Bracelets",
"Beaded Bracelets"
],
"used_manufacturer": false
},
{
"listing_id": 251636756,
"state": "active",
"user_id": 27935418,
"category_id": 69150555,
"title": "Scientific American 1899 Cruiser Atlanta Bicycle For Two",
"description": "Scientific American 1899 Cruiser Atlanta Bicycle For Two\r\n\r\nInventoryID: 3012\r\n\r\nFor more Scientific American\r\nhttps://www.etsy.com/shop/aniasattic/search?search_query=Scientific+American&order=date_desc&view_type=list&ref=shop_search \r\n\r\n",
"creation_tsz": 1444611663,
"ending_tsz": 1455242463,
"original_creation_tsz": 1444611663,
"last_modified_tsz": 1444611681,
"price": "16.00",
"currency_code": "USD",
"quantity": 1,
"tags": [
"Scientific American"
],
"category_path": [
"Books and Zines",
"Zine"
],
"category_path_ids": [
69150385,
69150555
],
"materials": [],
"shop_section_id": 17129732,
"featured_rank": null,
"state_tsz": 1444611663,
"url": "https://www.etsy.com/listing/251636756/scientific-american-1899-cruiser-atlanta?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 0,
"num_favorers": 0,
"shipping_template_id": 13961701074,
"processing_min": 1,
"processing_max": 3,
"who_made": "someone_else",
"is_supply": "false",
"when_made": "1800s",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": null,
"is_private": false,
"recipient": null,
"occasion": null,
"style": null,
"non_taxable": false,
"is_customizable": false,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": false,
"taxonomy_id": 2854,
"taxonomy_path": [
"Books, Movies & Music",
"Books",
"Zines & Magazines",
"Magazines"
],
"used_manufacturer": false
},
{
"listing_id": 251635204,
"state": "active",
"user_id": 37791158,
"category_id": 68889526,
"title": "Falcons Baby Onesie - Falcons Baby Jersey - Falcons Toddler T-Shirt - Personalized Falcons Baby Onesie",
"description": "Onesie Color: Black\nText Colors: White, Silver Metallic \n\nDADDY&#39;S LITTLE FALCONS FAN is the default but can be changed to MOMMY&#39;S, GRANDPA&#39;S etc. If you would like any changes please leave them in the NOTES TO SELLER upon checkout.\n\nThe adorable onesie&#39;s and t-shirts are Rabbit Skins brand and run true to size. They are 100% cotton and are machine wash and dry on low heat.The design is a high quality thin vinyl that is professionally applied and designed for use on children&#39;s apparel.\n\nPersonalization:\nSelect a onesie or t-shirt size from the drop down menu. A size chart is in a thumbnail under the picture of the bodysuit. Proceed to checkout. In the NOTES TO SELLER please copy and paste or leave the following:\n\nNAME:\nNUMBER: \n\nIMPORTANT \nPlease double-check your order notes to ensure you included all of the necessary, required information and correct spelling.\n\nCHECK YOUR ADDRESS as it will use the address that you have on file for billing. If you use PAYPAL it will use your PAYPAL billing address. If your order is returned there will be an additional shipping charge to resend the order.\n\nNew York Residents will be charged a 8% state sales tax, which will automatically be calculated and added to your shopping cart when checking out.\n\nLooking for removable NURSERY WALL DECALS? Visit my other shop Charming Vinyl Designs: https://www.etsy.com/shop/CharmingVinylDesigns?ref=si_shop\n\nThank you for shopping at Baby Threads Apparel.",
"creation_tsz": 1444610922,
"ending_tsz": 1455241722,
"original_creation_tsz": 1444610922,
"last_modified_tsz": 1444610923,
"price": "23.00",
"currency_code": "USD",
"quantity": 5,
"tags": [
"baby tees",
"baby gifts",
"onesie",
"baby bodysuits",
"baby bodysuits gifts",
"tees",
"baby",
"toddlers",
"personalized",
"t-shirts",
"jersey",
"Atlanta",
"Falcons"
],
"category_path": [
"Clothing",
"Children"
],
"category_path_ids": [
69150353,
68889526
],
"materials": [
"Cotton"
],
"shop_section_id": 16209799,
"featured_rank": null,
"state_tsz": 1444610922,
"url": "https://www.etsy.com/listing/251635204/falcons-baby-onesie-falcons-baby-jersey?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 0,
"num_favorers": 0,
"shipping_template_id": null,
"processing_min": 3,
"processing_max": 5,
"who_made": "i_did",
"is_supply": "false",
"when_made": "made_to_order",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": "in",
"is_private": false,
"recipient": "babies",
"occasion": null,
"style": null,
"non_taxable": false,
"is_customizable": false,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": true,
"taxonomy_id": 2122,
"taxonomy_path": [
"Clothing",
"Unisex Kids' Clothing",
"Unisex Baby Clothing"
],
"used_manufacturer": false
},
{
"listing_id": 205658822,
"state": "active",
"user_id": 52271679,
"category_id": 69150433,
"title": "NFL(r) Football Charms - Green Bay Packers Charms (10 pieces)",
"description": "This listing is for 10 pieces of NFL® GREEN BAY PACKERS charms. \n\nPlease select type in the menu!\n\nSizes: 22*15mm for the enamel  painted\n          20*11mm for the gold plated\n\nShipping is a flat rate of $2.95 and free for each additional item.\n\nCopyright BeadBoatUSA 2014",
"creation_tsz": 1444610350,
"ending_tsz": 1455241150,
"original_creation_tsz": 1412264512,
"last_modified_tsz": 1444610350,
"price": "5.00",
"currency_code": "USD",
"quantity": 85,
"tags": [
"charms",
"charm",
"NFL",
"football",
"Football charms",
"Denver Broncos",
"Indianapolis Colts",
"Atlanta Falcons",
"New York Jets",
"Seattle Seahawks",
"Houston Texans",
"New Orleans Saints",
"greenbay packers"
],
"category_path": [
"Supplies"
],
"category_path_ids": [
69150433
],
"materials": [
"pewter",
"enameled",
"enamel"
],
"shop_section_id": 16608314,
"featured_rank": null,
"state_tsz": 1441986675,
"url": "https://www.etsy.com/listing/205658822/nflr-football-charms-green-bay-packers?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 852,
"num_favorers": 61,
"shipping_template_id": 5372576642,
"processing_min": 1,
"processing_max": 2,
"who_made": "someone_else",
"is_supply": "true",
"when_made": "2010_2015",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": "in",
"is_private": false,
"recipient": null,
"occasion": null,
"style": null,
"non_taxable": false,
"is_customizable": false,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": true,
"taxonomy_id": 562,
"taxonomy_path": [
"Craft Supplies & Tools"
],
"used_manufacturer": false
},
{
"listing_id": 234534916,
"state": "active",
"user_id": 50143016,
"category_id": 69155215,
"title": "Atlanta Falcons Enamel Charm, Football Charm, NFL Charm, Sports Charm 19.5x23mm - ES529",
"description": "Atlanta Falcons Offical Team Logo Charm\n\nMaterial: Alloy & Enamel\n\nSize: 19.5x23mm\n\nQuantity: 1 charm\n\nYour order will be shipped within 24 Hours afer payment is received!\n\nWe hope to supply all kinds of DIY findings with competitive prices, so pls come back to our store frequently to check our new lists and preferential prices.\n\nEnjoy your shopping! And pls feel free to contact me!",
"creation_tsz": 1444610011,
"ending_tsz": 1455240811,
"original_creation_tsz": 1432470035,
"last_modified_tsz": 1444610011,
"price": "2.59",
"currency_code": "USD",
"quantity": 46,
"tags": [
"Commerical",
"Findings",
"supplies",
"enamel charm",
"enamel charms",
"enameled charm",
"NFL Charm",
"sports charm",
"enamel sports charm",
"enamel NFL charm",
"Atlanta Falcons",
"Atlanta charm",
"Falcons charm"
],
"category_path": [
"Accessories",
"Charm"
],
"category_path_ids": [
69150467,
69155215
],
"materials": [
"Alloy",
"Enamel"
],
"shop_section_id": 16203710,
"featured_rank": null,
"state_tsz": 1432470035,
"url": "https://www.etsy.com/listing/234534916/atlanta-falcons-enamel-charm-football?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 128,
"num_favorers": 12,
"shipping_template_id": 9123737644,
"processing_min": 1,
"processing_max": 1,
"who_made": "someone_else",
"is_supply": "true",
"when_made": "2010_2015",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": "in",
"is_private": false,
"recipient": null,
"occasion": null,
"style": null,
"non_taxable": false,
"is_customizable": true,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": false,
"taxonomy_id": 697,
"taxonomy_path": [
"Craft Supplies & Tools",
"Jewelry & Beading Supplies",
"Charms"
],
"used_manufacturer": false
},
{
"listing_id": 201203118,
"state": "active",
"user_id": 52271679,
"category_id": 69150433,
"title": "NFL(r) Football Charms - Tennessee Titans Charms (10 Pieces)",
"description": "This listing is for 10 pieces of NFL® Tennessee Titans charms. All charms are officially licensed by the NFL®\r\n\r\nShipping is a flat rate of $2.95 and free for each additional item.\r\n\r\nCopyright BeadBoatUSA 2014",
"creation_tsz": 1444609954,
"ending_tsz": 1455240754,
"original_creation_tsz": 1409021505,
"last_modified_tsz": 1444609954,
"price": "10.00",
"currency_code": "USD",
"quantity": 5,
"tags": [
"charms",
"charm",
"NFL",
"football",
"Football charms",
"Denver Broncos",
"Indianapolis Colts",
"Atlanta Falcons",
"New York Jets",
"Seattle Seahawks",
"Houston Texans",
"New York Giants",
"Tennessee Titans"
],
"category_path": [
"Supplies"
],
"category_path_ids": [
69150433
],
"materials": [
"pewter",
"enameled",
"enamel"
],
"shop_section_id": 16608314,
"featured_rank": null,
"state_tsz": 1435761703,
"url": "https://www.etsy.com/listing/201203118/nflr-football-charms-tennessee-titans?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 137,
"num_favorers": 13,
"shipping_template_id": 5372576642,
"processing_min": 1,
"processing_max": 2,
"who_made": "someone_else",
"is_supply": "true",
"when_made": "2010_2015",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": null,
"is_private": false,
"recipient": null,
"occasion": null,
"style": null,
"non_taxable": false,
"is_customizable": true,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": false,
"suggested_taxonomy_id": 562,
"taxonomy_path": [
"Craft Supplies & Tools"
],
"used_manufacturer": false
},
{
"listing_id": 199529768,
"state": "active",
"user_id": 13142868,
"category_id": 68892062,
"title": "Atlanta Graffiti Watercolor Skyline Wedding Invitation Watercolor Invitation / Modern Invitation / New York / Toronto / San Francisco",
"description": "Unique, modern, hip and funky - this invitation will show your city pride! The colours make it perfect for any season, and can be altered slightly to suit your theme. Additional cities are available. \n\n*************************************************************************\nWHAT&#39;S INCLUDED\n*************************************************************************\n\n* Invitation as shown in the listing printed on 100lb cardstock\n* White mailer envelope.\n\nWant to purchase a sample? Simply purchase one of this listing and enter coupon code &quot;SAMPLEPRODUCT&quot; at checkout and we&#39;ll mail you a stock sample, shipping on us!\n\n\n*************************************************************************\nADDITIONAL UPGRADE OPTIONS\n*************************************************************************\n\nFor items you desire that are not included above (ex: RSVP cards, map design, additional inserts, guest address printing, etc), please visit:\n\nwww.etsy.com/ca/shop/PolkaDotInvites?section_id=13902462\n\nPlease contact us to find out what upgrade options are available for this particular invitation, before purchasing upgrades. You do NOT need to purchase any upgrade options that are already listed above in the description of the invitation. \n\n*************************************************************************\nTO ORDER\n*************************************************************************\n\nPlease include the wording you would like on the invitation in the NOTES section of the order. Please be sure to remember to include wording for all inserts as well - and if you qualify for free return address printing, or have chose this upgrade - please include the exact return address you wish to have printed. WE WILL SEND YOU A DIGITAL SAMPLE FOR APPROVAL PRIOR TO PRINTING. Whatever you approve is ultimately what gets printed. Please be sure to read over the proof carefully to avoid any typos appearing on your actual invitation. \n\n\n*************************************************************************\nTURN AROUND TIME (printed products only)\n*************************************************************************\n\nA digital sample of your invitation will be emailed to you via Etsy within 3-4 business days. \nThe completion of your invitation order will depend entirely on the complexity of the invitation. Printed invitations usually take 1-2 weeks, whereas embellished invitations - and invites in pockets or folders can take 4-6 weeks. Please contact us if you are working on a specific time line, as we are usually able to accommodate rush orders, including same week shipments.ut shipping if you are unsure and we will do our best to help!!",
"creation_tsz": 1444609796,
"ending_tsz": 1455240596,
"original_creation_tsz": 1407772721,
"last_modified_tsz": 1444609796,
"price": "2.50",
"currency_code": "CAD",
"quantity": 997,
"tags": [
"watercolor",
"watercolour",
"vintage invitation",
"painting",
"natural invitation",
"invite",
"Atlanta",
"san francisco",
"modern invitation",
"modern wedding",
"modern invite",
"new york",
"toronto"
],
"category_path": [
"Weddings",
"Invitation"
],
"category_path_ids": [
68887494,
68892062
],
"materials": [],
"shop_section_id": 10514626,
"featured_rank": null,
"state_tsz": 1443825650,
"url": "https://www.etsy.com/listing/199529768/atlanta-graffiti-watercolor-skyline?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 315,
"num_favorers": 8,
"shipping_template_id": 598520256,
"processing_min": 10,
"processing_max": 15,
"who_made": "i_did",
"is_supply": "false",
"when_made": "made_to_order",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": "in",
"is_private": false,
"recipient": null,
"occasion": null,
"style": null,
"non_taxable": false,
"is_customizable": true,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": true,
"taxonomy_id": 1676,
"taxonomy_path": [
"Weddings",
"Invitations & Paper",
"Invitations"
],
"used_manufacturer": false
},
{
"listing_id": 251630542,
"state": "active",
"user_id": 40697690,
"category_id": 69154933,
"title": "ATLANTA FALCONS Home (red) or Away (white) &quot;Jersey Photo&quot; Personalize ANY Name & Number in size 5x7 8x10 11x14 16x20 Football Picture Print",
"description": "* Picture frame & matting are not included with your purchase\n* &quot;Watermark&quot; on Etsy listing photo will NOT appear on your photo\n\nATLANTA FLACONS digital &quot;Jersey Photo&quot; done in your choice of the Falcons modern Home (red) or Away (white) jersey.  Sizes available in 5x7, 8x10, 11x14 or 16x20.  Simply add your own frame/matting and display!  Add Jersey photos to your sports room and create your own Wall of Fame\n\n* Choose a photo size/color and player name/number from the drop down box at the top, right.  You can also personalize your jersey photo with a family member / friends name & number or custom your photo with a player not listed.\n\n** HOW TO PERSONALIZE OR CUSTOM YOUR JERSEY PHOTO:\nClick the &quot;Custom Request&quot; button above and let me know which name/number & photo size you want\n\n** THERE IS NO ADDITIONAL CHARGE TO PERSONALIZE OR CUSTOM YOUR JERSEY PHOTO\n\n*  Digital Jersey Photos are designed with high resolution graphics and produced on an Epson Stylus Professional 3880 with K3 Ultrachrome Color Technology, using thick stock, professional satin luster professional photo paper, providing archival longevity and image quality, for eye-popping color and black & white photos as well as providing water/smudge resistance and reduced glare technology (essential for glass framing)\n\n* PICTURE FRAME & MATTING ARE NOT INCLUDED WITH PURCHASE AND ARE ONLY VISUAL SAMPLES FOR DISPLAY IDEAS\n*  Jersey Photos are available in 5x7, 8x10, 11x14 and 16x20 sizes (all sizes are exact to outside border)\n*  Sizes fit any standard 5x7, 8x10, 11x14 or 16x20 matting, picture or poster frames\n*  FREE SHIPPING on every item in our store, whether you buy 1 or 100!\n*  Currently only accepting orders with a United States shipping address\n\nClick link below to view all Jersey Photos:\nhttps://www.etsy.com/shop/6StarGraphs?section_id=16206239&ref=shopsection_leftnav_3",
"creation_tsz": 1444608711,
"ending_tsz": 1455239511,
"original_creation_tsz": 1444608711,
"last_modified_tsz": 1444608712,
"price": "7.95",
"currency_code": "USD",
"quantity": 6,
"tags": [
"matt ryan",
"julio jones",
"davonta freeman",
"steve bartkowski",
"william andrews",
"deion sanders",
"atlanta braves"
],
"category_path": [
"Art",
"Printmaking"
],
"category_path_ids": [
68887312,
69154933
],
"materials": [
"Professional Photographic Paper"
],
"shop_section_id": 16206239,
"featured_rank": null,
"state_tsz": 1444608711,
"url": "https://www.etsy.com/listing/251630542/atlanta-falcons-home-red-or-away-white?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 0,
"num_favorers": 0,
"shipping_template_id": null,
"processing_min": 1,
"processing_max": 1,
"who_made": "i_did",
"is_supply": "false",
"when_made": "2010_2015",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": "in",
"is_private": false,
"recipient": null,
"occasion": null,
"style": null,
"non_taxable": false,
"is_customizable": true,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": true,
"taxonomy_id": 119,
"taxonomy_path": [
"Art & Collectibles",
"Prints"
],
"used_manufacturer": false
},
{
"listing_id": 224063563,
"state": "active",
"user_id": 25522665,
"category_id": 68888310,
"title": "ATLANTA HAWKS - 7/8&quot; Grosgrain Logo Ribbon - 3 Yards",
"description": "This listing is for 3 yards of Atlanta Hawks 7/8&quot; grosgrain logo ribbon, as pictured. 100% polyester, this ribbon is ideal for team-related craft items, hair bows, decorations and scrapbooks.  Ribbon ships in a protective mailer via USPS First Class Mail with tracking. Please contact me with any questions prior to purchase. Thanks for visiting my shop!",
"creation_tsz": 1444608639,
"ending_tsz": 1455239439,
"original_creation_tsz": 1424897171,
"last_modified_tsz": 1444608639,
"price": "3.99",
"currency_code": "USD",
"quantity": 2,
"tags": [
"team ribbon",
"craft ribbon",
"sports team ribbon",
"hair bows",
"hair bow ribbon",
"hairbow ribbon",
"decorative ribbon",
"NBA team ribbon",
"NBA ribbon",
"basketball ribbon",
"Atlanta Hawks",
"Hawks ribbon"
],
"category_path": [
"Supplies",
"Fabric"
],
"category_path_ids": [
69150433,
68888310
],
"materials": [
"polyester"
],
"shop_section_id": 13818304,
"featured_rank": null,
"state_tsz": 1435175155,
"url": "https://www.etsy.com/listing/224063563/atlanta-hawks-78-grosgrain-logo-ribbon-3?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 25,
"num_favorers": 0,
"shipping_template_id": 1365571588,
"processing_min": 1,
"processing_max": 2,
"who_made": "someone_else",
"is_supply": "true",
"when_made": "2010_2015",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": null,
"is_private": false,
"recipient": null,
"occasion": null,
"style": null,
"non_taxable": false,
"is_customizable": true,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": false,
"taxonomy_id": 574,
"taxonomy_path": [
"Craft Supplies & Tools",
"Fabric"
],
"used_manufacturer": false
},
{
"listing_id": 251630328,
"state": "active",
"user_id": 27042546,
"category_id": 68900036,
"title": "Philadelphia Flyers.... License Plate BirdHouse.",
"description": "Phladelphia Flyers.... Bird House.\n- Measures 13&quot; long, 9&quot; deep and 9&quot; tall.\n- Made from 3/4&quot; pine boards. Torched to darken and bring out the wood grain.\n- Painted with exterior paint to match the Team colors.\n- The hole is 1 1/2&quot; with a natural sassafras perch.\n- Wire attached for easy hanging. Remove screws on bottom for cleaning.\n\nWhat a GREAT Gift...thanks for visiting...",
"creation_tsz": 1444608597,
"ending_tsz": 1455239397,
"original_creation_tsz": 1444608597,
"last_modified_tsz": 1444608598,
"price": "30.00",
"currency_code": "USD",
"quantity": 1,
"tags": [
"bird house",
"yard",
"lawn ornament",
"gift",
"sports fan",
"bird lover",
"atlanta",
"football",
"chicago",
"Falcons",
"Detroit",
"Red Wings",
"hockey"
],
"category_path": [
"Housewares",
"Outdoor",
"Garden Decor"
],
"category_path_ids": [
69150425,
68891508,
68900036
],
"materials": [
"wood",
"screws",
"paint"
],
"shop_section_id": 13332155,
"featured_rank": null,
"state_tsz": 1444608597,
"url": "https://www.etsy.com/listing/251630328/philadelphia-flyers-license-plate?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 0,
"num_favorers": 0,
"shipping_template_id": null,
"processing_min": 1,
"processing_max": 1,
"who_made": "i_did",
"is_supply": "false",
"when_made": "2010_2015",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": "in",
"is_private": false,
"recipient": "unisex_adults",
"occasion": "fathers_day",
"style": [
"Rustic",
"Country Western"
],
"non_taxable": false,
"is_customizable": true,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": false,
"taxonomy_id": 1957,
"taxonomy_path": [
"Home & Living",
"Outdoor & Gardening",
"Feeders & Birdhouses",
"Birdhouses"
],
"used_manufacturer": false
},
{
"listing_id": 244255555,
"state": "active",
"user_id": 8402347,
"category_id": 69151567,
"title": "Georgia State Necklace, Stainless Steel State, Georgia State Pendant, Atlanta Heart Capital, Love State Necklace, Under 20 USA8",
"description": "- Stainless Steel Pendant - USA Georgia State - delicate heart cut away approx.\n   location of Atlanta Capital of Georgia - Pendant :\n Georgia State Map Charm  - approx. 30 x 18mm (  1  1/8 &quot; x 6/8 &quot;) \n  Thickness approx. 2mm \n\n- Stainless Steel is hypo allergenic, it doesn’t rust, change colour or tarnish\n- Lobster Claw Clasp is slightly larger for easier use.\n- Ready to ship - no wait time \n- Your jewelry will arrive wrapped & in a pretty organza gift bag.\n\n- To add a Swarovski birthstone $3.50 \nhttps://www.etsy.com/listing/194690319/add-on-a-finished-swarovski-drop?ref=shop_home_active_2\n\nI ship same day or within 48 hours\nThank you for visiting my little shop.\n\nAlthough I have tried to visually represent this item to the best of my \nability, do take note that there may be some slight colour variation due \nto differences in monitor displays and settings. Please note the size \nreferences as these photos are close ups and item may appear larger \nthan it actually is.\n\n:*¨¨*:•..•:*¨¨*:•..•:*¨¨*:•..•:*¨¨*:•..•:*¨¨*:•..•:*¨¨*:•.•:*¨¨*:•.•:*¨¨*:•.•:*¨¨*:•\nPlease add my shop as a ♥FAVORITE♥ so you can find me!\n•:*¨¨*:•..•:*¨¨*:•..•:*¨¨*:•..•:*¨¨*:•..•:*¨¨*:•..•:*¨¨*:• .•:*¨¨*:•.•:*¨¨*:• .•:*¨¨*",
"creation_tsz": 1444608457,
"ending_tsz": 1455239257,
"original_creation_tsz": 1439690302,
"last_modified_tsz": 1444608457,
"price": "17.99",
"currency_code": "USD",
"quantity": 40,
"tags": [
"handmade",
"trip souvenir",
"menento",
"country necklace",
"personalize necklace",
"gift for her",
"under 20",
"transfer student",
"Georgia",
"Georgia state",
"Atlanta",
"Georgia map necklace",
"state love heart"
],
"category_path": [
"Jewelry",
"Necklace"
],
"category_path_ids": [
68887482,
69151567
],
"materials": [
"stainless steel",
"Stainless steel pendant",
"Stainless steel Georgia state necklace",
"love Atlanta"
],
"shop_section_id": 15676580,
"featured_rank": null,
"state_tsz": 1439773078,
"url": "https://www.etsy.com/listing/244255555/georgia-state-necklace-stainless-steel?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 7,
"num_favorers": 0,
"shipping_template_id": 933080068,
"processing_min": 1,
"processing_max": 3,
"who_made": "i_did",
"is_supply": "false",
"when_made": "2010_2015",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": "in",
"is_private": false,
"recipient": null,
"occasion": null,
"style": [
"Traditional"
],
"non_taxable": false,
"is_customizable": false,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": true,
"taxonomy_id": 1229,
"taxonomy_path": [
"Jewelry",
"Necklaces",
"Pendants"
],
"used_manufacturer": false
},
{
"listing_id": 209198345,
"state": "active",
"user_id": 44999576,
"category_id": 69170137,
"title": "Baseball Machine Embroidery Designs (badgers of wisconsin) 4x4 - Instant Download",
"description": "Baseball Machine Embroidery Designs (badgers of wisconsin)  4x4 - Instant Download. Professionally digitized. You wont find a better quality. \r\n\r\nNo auto-conversion employed. Digitized from scratch. This design will run smooth and without any problem. Just follow the guidelines in the PDF file. \r\n\r\nDescription. \r\nFill stitches. 2.87&quot; w  x  2.67&quot; h.   9014 stitches.\r\n\r\nThe design will come in the following formats: DST, EXP, JEF, and PES.\r\n\r\nIf you wish to have a different format, please send me a message.\r\n\r\nAvailable formats:\r\n\r\nBernina: EXP, ART (grade C)\r\nTajima: DST\r\nMelco: EXP\r\nBrother: PES\r\nJanome/Elna: SEW\r\nJanome/Elna: JEF\r\nHusqvarna/Viking/PFAFF: HUS, VIP, VP3\r\nSinger/Compucon: XXX\r\n\r\n\r\n*************TERMS OF USE************\r\nYou may NOT copy, share, sell digital or reproduced my designs in any format as your own.\r\n\r\nIf you re-size, convert or edit my designs in any manner, I can not be responsible for the quality of design.\r\n\r\nAll sales are final, due to the nature of item.\r\n\r\nThanks for your visit!",
"creation_tsz": 1444608348,
"ending_tsz": 1455239148,
"original_creation_tsz": 1414732420,
"last_modified_tsz": 1444608348,
"price": "5.00",
"currency_code": "USD",
"quantity": 3,
"tags": [
"embroidery patterns",
"embroidery designs",
"football embroidery",
"digitized designs",
"raiders embroidery",
"braves embroidery",
"atlanta embroidery",
"baseball embroidery",
"dodgers embroidery",
"badgers embroidery",
"wisconsin embroidery"
],
"category_path": [
"Patterns",
"Embroidery",
"Machine Embroidery"
],
"category_path_ids": [
68887486,
69152485,
69170137
],
"materials": [],
"shop_section_id": 15098755,
"featured_rank": null,
"state_tsz": 1438015245,
"url": "https://www.etsy.com/listing/209198345/baseball-machine-embroidery-designs?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 177,
"num_favorers": 13,
"shipping_template_id": null,
"processing_min": null,
"processing_max": null,
"who_made": "i_did",
"is_supply": "false",
"when_made": "2010_2015",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": null,
"is_private": false,
"recipient": "unisex_adults",
"occasion": "birthday",
"style": null,
"non_taxable": false,
"is_customizable": false,
"is_digital": true,
"file_data": "1 ZIP",
"language": "en-US",
"has_variations": false,
"suggested_taxonomy_id": 729,
"taxonomy_path": [
"Craft Supplies & Tools",
"Patterns & Tutorials"
],
"used_manufacturer": false
},
{
"listing_id": 122491985,
"state": "active",
"user_id": 64040,
"category_id": 68892008,
"title": "Atlanta Art- City State Art Box Sign 11&quot; x 14&quot; Atlanta Map Art- Georgia State Print- Going Away Gifts- Atlanta Gifts- Georgia Gifts for Him",
"description": "My Atlanta City State Art Print mounted on a 11&quot; x 14&quot; x 1 5/8&quot; D Birch Art Box. Image is applied and sealed using a non-toxic water-based sealer. Block sides are left natural and also sealed with the same clear sealer. Box can sit on a shelf or other flat surface or hang on the wall.\n\nInspired by highway signs, I combined that imagery with chalkboard textures to create this retro-styled artwork.\n\nListing is for one (1) 11&quot; x 14&quot; Atlanta City State Art Box. If you are looking for another state, please check out my State Map Art and Hoods section for listings for all 50 states. If you want a different city in this state, you can use the pull-down menu to the right to specify that this is a custom piece. Then just tell me the city in the message to seller during checkout.\n\nImages are digitally created and reproduced on archival paper. Image size is around 11&quot; x 14&quot;.\n\nItem is not a toy and is not for use or handling by children. Item should be displayed out of reach of children under 12 years of age. I recommend using museum putty on the bottom edge or base to stabilize any art pieces that are displayed on shelves and the like in in a child&#39;s room.\n\n------------------------\n\nI make these as I sell them, especially for you. Blocks and art boxes usually leave here in 10-14 business days. During times of high order volume, turnaround may be longer. If you need an item more quickly, please contact me.\n\n\nLike what you see? Favorite my shop to stay up-to-date on my newest work on your Etsy home page!\n\n^^^",
"creation_tsz": 1444607901,
"ending_tsz": 1455238701,
"original_creation_tsz": 1359858415,
"last_modified_tsz": 1444607901,
"price": "75.00",
"currency_code": "USD",
"quantity": 6,
"tags": [
"Black And White Art",
"Chalkboard Art",
"Atlanta Art",
"Atlanta Map Art",
"Vintage Look Art",
"Minimalist Art",
"Honeymoon Gift",
"United States Cities",
"Dorm Room Art",
"Georgia State Print",
"Going Away Gifts",
"Georgia Gifts Him",
"Box Signs"
],
"category_path": [
"Housewares",
"Home Decor"
],
"category_path_ids": [
69150425,
68892008
],
"materials": [
"wood",
"paper",
"ink",
"glue",
"sealer"
],
"shop_section_id": 12817829,
"featured_rank": null,
"state_tsz": 1431393542,
"url": "https://www.etsy.com/listing/122491985/atlanta-art-city-state-art-box-sign-11-x?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 937,
"num_favorers": 66,
"shipping_template_id": null,
"processing_min": 10,
"processing_max": 14,
"who_made": "i_did",
"is_supply": "false",
"when_made": "made_to_order",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": null,
"is_private": false,
"recipient": "unisex_adults",
"occasion": "housewarming",
"style": [
"Modern",
"Rustic"
],
"non_taxable": false,
"is_customizable": false,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": true,
"taxonomy_id": 1002,
"taxonomy_path": [
"Home & Living",
"Home Décor"
],
"used_manufacturer": false
},
{
"listing_id": 250159520,
"state": "active",
"user_id": 73319956,
"category_id": 68887312,
"title": "Atlanta Falcons Football Logo Design Cutting File in Svg, Eps, Dxf, and Jpeg Format for Cricut and Silhouette",
"description": "This is a digital download of a Atlanta Falcons logo design cutting file. With this purchase, you will receive a zipped folder containing this image in SVG, DXF, EPS, and JPEG form, suitable for use in Cricut Design Space, Sure Cuts A Lot, Make The Cut, and the Silhouette Basic and/or Designer Edition. \n\nThese files are available for PERSONAL and SMALL BUSINESS COMMERCIAL use.\n\nHowever, you MAY NOT:\n- use any part of these files to resell digitally in any format\n- share or sell these files for any reason\n\nDue to the nature of instant downloads, I do not offer refunds. Therefore, please make sure you check (and double-check!) the file type you need prior to making your purchase.",
"creation_tsz": 1444606761,
"ending_tsz": 1455237561,
"original_creation_tsz": 1443641744,
"last_modified_tsz": 1444606761,
"price": "1.99",
"currency_code": "USD",
"quantity": 97,
"tags": [
"svg eps dxf jpg jpeg",
"cricut design space",
"silhouette studio",
"vector file art",
"cut file clipart",
"cutting file",
"vinyl htv iron on",
"shirt decal glass",
"sport sports school",
"football helmet",
"htv shirt decal",
"logo word",
"Atlanta Falcons"
],
"category_path": [
"Art"
],
"category_path_ids": [
68887312
],
"materials": [
"vinyl",
"htv",
"heat transfer",
"iron on",
"decal",
"cardstock",
"paper"
],
"shop_section_id": 17870989,
"featured_rank": null,
"state_tsz": 1443641744,
"url": "https://www.etsy.com/listing/250159520/atlanta-falcons-football-logo-design?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 29,
"num_favorers": 3,
"shipping_template_id": null,
"processing_min": null,
"processing_max": null,
"who_made": "i_did",
"is_supply": "true",
"when_made": "2010_2015",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": "in",
"is_private": false,
"recipient": null,
"occasion": null,
"style": null,
"non_taxable": false,
"is_customizable": false,
"is_digital": true,
"file_data": "1 ZIP",
"language": "en-US",
"has_variations": false,
"taxonomy_id": 2817,
"taxonomy_path": [
"Art & Collectibles",
"Clip Art"
],
"used_manufacturer": false
},
{
"listing_id": 231823681,
"state": "active",
"user_id": 5070255,
"category_id": 69150455,
"title": "GEORGIA LOVE TOTE Atlanta red state silhouette with heart on natural bag",
"description": "United States silhouettes with a heart over your favorite city: Atlanta!!\nThese make great wedding welcome bags and party favors.\n\nNatural Tote is ultra lightweight tote that is ethically sourced: fair-wage and fair-labor certified, made of 100% recycled cotton.\n\nTote Size: 16&quot;W x 15.5&quot;H; 3&quot;Gusset (Bottom), Handles are 10&quot; in length\n\nLarge orders welcome - custom colors or cities available when buying 12+ totes. Discount available for 24+ totes. For custom options and bulk pricing please use this listing: https://www.etsy.com/listing/203600018 \n\nSee all our State Love products here: https://www.etsy.com/shop/vital?section_id=15870679",
"creation_tsz": 1444606667,
"ending_tsz": 1455237467,
"original_creation_tsz": 1430420468,
"last_modified_tsz": 1444606667,
"price": "15.00",
"currency_code": "USD",
"quantity": 12,
"tags": [
"canvas",
"medium",
"screenprint",
"market",
"natural",
"grocery bag",
"gift",
"States",
"Sun Belt",
"Texas pride",
"Home State",
"H-Town",
"State Silhouette"
],
"category_path": [
"Bags and Purses"
],
"category_path_ids": [
69150455
],
"materials": [
"tote",
"ink"
],
"shop_section_id": 15870679,
"featured_rank": null,
"state_tsz": 1430420470,
"url": "https://www.etsy.com/listing/231823681/georgia-love-tote-atlanta-red-state?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 42,
"num_favorers": 4,
"shipping_template_id": 6436898,
"processing_min": 1,
"processing_max": 2,
"who_made": "collective",
"is_supply": "false",
"when_made": "2010_2015",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": "in",
"is_private": false,
"recipient": null,
"occasion": null,
"style": null,
"non_taxable": false,
"is_customizable": false,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": true,
"taxonomy_id": 190,
"taxonomy_path": [
"Bags & Purses",
"Totes"
],
"used_manufacturer": false
},
{
"listing_id": 242277253,
"state": "active",
"user_id": 49580612,
"category_id": 69151567,
"title": "Map of Georgia - Map Pendant Necklace - Custom Jewelry - Personalized Pendant - Atlanta Georgia - Travel Jewelry - USA State Jewelry",
"description": "This necklace features a map of Georgia on a 1&quot; (25mm) round antique brass coloured pendant that is covered in clear domed glass.\n\nPlease choose which charm you would by referring to the 4th photo and selecting from the options menu.   The charms vary quite a bit in size, ranging from about 11mm for the smallest to about 34mm for the largest, so choose accordingly. \n\nPlease choose which colour of bead you would like by referring to the 5th photo and selecting from the option menu.\n\nThe antique brass ball chain is 24&quot; (61cm) but can be shortened upon request. If you would prefer a rolo chain, please leave a note in the message to seller box at checkout.\n\nPlease note that this necklace is not waterproof. Please remove before showering or swimming.\n\nEach necklace is made to order and some small variations are expected. That is the beauty of handmade. Some small bubbles can occur. \n\nAll measurements are approximate.\n\nCheck out all of my map and globe necklaces here:\nhttps://www.etsy.com/shop/OxfordBright?section_id=15636070&ref=shopsection_leftnav_1\n\nOr shop my entire store here:\noxfordbright.etsy.com\n\nI take great care to ensure my photos are accurate but please keep in mind that all monitors are different.\n\nIf you are interested in a custom map or quote necklace, please feel free to contact me. I love to create unique and beautiful pieces with a map of the country/city that has stolen your heart :)\n\nTo see examples of my custom work, visit Sew Lovely Designs on facebook or Instagram @bethany_oxfordbright",
"creation_tsz": 1444604826,
"ending_tsz": 1455235626,
"original_creation_tsz": 1438267022,
"last_modified_tsz": 1444604826,
"price": "19.00",
"currency_code": "USD",
"quantity": 5,
"tags": [
"antique brass",
"sew lovely designs",
"made in canada",
"personalized",
"personalized gift",
"bead charm necklace",
"custom jewelry",
"custom map jewelry",
"map of united states",
"state jewelry peach",
"map of georgia",
"map pendant necklace",
"atlanta jewelry usa"
],
"category_path": [
"Jewelry",
"Necklace"
],
"category_path_ids": [
68887482,
69151567
],
"materials": [
"czech glass bead",
"anitque brass jump ring",
"ball chain",
"glass dome",
"circle pendant",
"charm"
],
"shop_section_id": 15636070,
"featured_rank": null,
"state_tsz": 1438267022,
"url": "https://www.etsy.com/listing/242277253/map-of-georgia-map-pendant-necklace?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 25,
"num_favorers": 2,
"shipping_template_id": 5544974060,
"processing_min": 3,
"processing_max": 5,
"who_made": "i_did",
"is_supply": "false",
"when_made": "made_to_order",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": "in",
"is_private": false,
"recipient": null,
"occasion": null,
"style": [
"Modern"
],
"non_taxable": false,
"is_customizable": false,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": true,
"taxonomy_id": 1222,
"taxonomy_path": [
"Jewelry",
"Necklaces",
"Charm Necklaces"
],
"used_manufacturer": false
},
{
"listing_id": 251620470,
"state": "active",
"user_id": 21979833,
"category_id": 69187747,
"title": "Falcons Headband.Atlanta Falcons Headband.Falcons Baby Headband.Baby Headband.Newborn Headband.Sports Headband.Football Headband.Falcons Bow",
"description": "This fabulous Atlanta Falcons headband has two shabby chic flowers with a logo embellishment in the center on a soft white elastic. Perfect for football Sundays when wanting to represent your favorite team, but also for everyday wear! This lovely black, red and white headband can also be used as a photography prop, and it looks fabulous on any age! \n\nNew FB fans receive 15% off your first purchase! Just message me and I will send you the coupon code! Year-round special sales and promotions ONLY publicized on FB. \n\nhttp://www.facebook.com/rosesandpolkadots\n\nFollow us on Instagram @rosesandpolkadots and tag your photos #rosesandpolkadotsboutique\n\n\nSizes:\n\n13&quot; Newborn\n14&quot; 3-6 months\n15&quot; 6 months-2 years\n16&quot; 2 years-Tween\n18&quot; Adult\n\nPlease select a headband size or leave a message in the &quot;note to seller&quot; box at the checkout. If you would like to guarantee the item to fit, please measure size of head and order accordingly. If you don&#39;t specify a size, a 15&quot; will ship. Other elastic available. Just message me at checkout.\n\nPlease read our shop policies, including our ship times, so you are aware of policies surrounding all transactions with our shop.\n Have any questions? Contact the shop owner.",
"creation_tsz": 1444603687,
"ending_tsz": 1455234487,
"original_creation_tsz": 1444603687,
"last_modified_tsz": 1444603687,
"price": "7.95",
"currency_code": "USD",
"quantity": 15,
"tags": [
"Newborn Headbands",
"Baby Headbands",
"Baby Girl Headbands",
"Girl Headband",
"Football Headband",
"Sports Headband",
"Baby Sports Headband",
"baby girl bow",
"baby",
"Atlanta Falcons",
"Atlanta Falcons Bow",
"Falcons Headband",
"Falcons Bow"
],
"category_path": [
"Accessories",
"Hair",
"Headband"
],
"category_path_ids": [
69150467,
69153737,
69187747
],
"materials": [],
"shop_section_id": 12879374,
"featured_rank": null,
"state_tsz": 1444603687,
"url": "https://www.etsy.com/listing/251620470/falcons-headbandatlanta-falcons?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 0,
"num_favorers": 0,
"shipping_template_id": null,
"processing_min": 3,
"processing_max": 5,
"who_made": "i_did",
"is_supply": "false",
"when_made": "2010_2015",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": "in",
"is_private": false,
"recipient": "baby_girls",
"occasion": null,
"style": null,
"non_taxable": false,
"is_customizable": true,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": true,
"taxonomy_id": 2906,
"taxonomy_path": [
"Accessories",
"Hair Accessories",
"Headbands & Turbans",
"Baby Headbands"
],
"used_manufacturer": false
},
{
"listing_id": 220985143,
"state": "active",
"user_id": 20898500,
"category_id": 69150425,
"title": "Atlanta Falcons Mason Jar Travel Mug",
"description": "Perfect for your hot coffee, iced coffee, water, tea, lemonade, smoothie and more! Drinking out of glass is proven to be better for your health and this mason jar mug is the solution. (And it&#39;s really cute too!)\n\nEco-friendly. Also makes a great teacher gift, housewarming gift, or thank you gift!\n\nHandmade sleeve is crafted from 2-layers of cotton fabric and is machine-washable. Air dry sleeve to avoid shrinking. All parts are dishwasher safe, though we do recommend hand washing the metal ring to avoid rusting. Launder your sleeve if your fabric should become loose (as cotton likes to do after repetitive use).\n\nSet includes:\nRegular mouth pint mason jar (16 oz.)\nBPA-free sipper lid\nBPA-free reusable straw\nHand-sewn cotton sleeve \nMason jar metal ring\n\n*Please note that top-stitching thread and/or button color may vary, but will, of course, always be coordinating! Should you require a specific thread or button color, please note that in your order.",
"creation_tsz": 1444603238,
"ending_tsz": 1455234038,
"original_creation_tsz": 1422844078,
"last_modified_tsz": 1444603238,
"price": "14.00",
"currency_code": "USD",
"quantity": 2,
"tags": [
"fabric sleeve",
"fabric cozy",
"koozie",
"travel mug",
"teacher gift",
"mason jar mug",
"mason jar travel mug",
"mason jar koozie",
"mason jar cozy",
"glass mug",
"glass travel mug",
"mason jar tumbler"
],
"category_path": [
"Housewares"
],
"category_path_ids": [
69150425
],
"materials": [],
"shop_section_id": 16943475,
"featured_rank": null,
"state_tsz": 1433297435,
"url": "https://www.etsy.com/listing/220985143/atlanta-falcons-mason-jar-travel-mug?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 14,
"num_favorers": 0,
"shipping_template_id": null,
"processing_min": 3,
"processing_max": 5,
"who_made": "i_did",
"is_supply": "false",
"when_made": "made_to_order",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": "in",
"is_private": false,
"recipient": null,
"occasion": null,
"style": null,
"non_taxable": false,
"is_customizable": true,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": false,
"taxonomy_id": 1063,
"taxonomy_path": [
"Home & Living",
"Kitchen & Dining",
"Drink & Barware",
"Drinkware",
"Cozies"
],
"used_manufacturer": false
}
],
"params": {
"limit": 25,
"offset": 0,
"page": null,
"keywords": "atlanta",
"sort_on": "created",
"sort_order": "down",
"min_price": null,
"max_price": null,
"color": null,
"color_accuracy": 0,
"tags": null,
"category": null,
"location": null,
"lat": null,
"lon": null,
"region": null,
"geo_level": "city",
"accepts_gift_cards": "false",
"translate_keywords": "false"
},
"type": "Listing",
"pagination": {
"effective_limit": 25,
"effective_offset": 0,
"next_offset": 25,
"effective_page": 1,
"next_page": 2
}
}